# Docker compose to spin up aries-controller's for testing multi agent and multi controller combinations
# sa-sc = single agent single controller
# ma-mc = multi agent multi controller
# (and then all 4 combinations)
#
version: '3.5'

networks:
    agency-network:
        external: true

services:
    sa-sc-controller:
        environment:
            - MULTI_AGENT=false
            - MULTI_CONTROLLER=false
            - WALLET_ID=sascwallet
            - WALLET_KEY=sascwalletkey
            - SEED=000000000000000000000000Steward1
            - AGENT_ID=sascagent
            - PORT=3030
            - SELF_URL=http://sa-sc-controller:3030
            - ADMIN_API_KEY=sascAdminApiKey
        build:
            context: .
            dockerfile: Dockerfile
        image: sa-sc-controller
        container_name: sa-sc-controller
        ports:
            - "3030:3030"
        volumes:
            - ./:/www
            # - ../protocol-common/dist:/www/node_modules/protocol-common
        networks:
            - agency-network
        tty: true

    sa-mc-controller:
        environment:
            - MULTI_AGENT=false
            - MULTI_CONTROLLER=true
            - PORT=3031
            - SELF_URL=http://sa-mc-controller:3031
        build:
            context: .
            dockerfile: Dockerfile
        image: sa-mc-controller
        container_name: sa-mc-controller
        ports:
            - "3031:3031"
        volumes:
            - ./:/www
        networks:
            - agency-network
        tty: true

    ma-sc-controller:
        environment:
            - MULTI_AGENT=true
            - MULTI_CONTROLLER=false
            - WALLET_ID=mascwallet
            - WALLET_KEY=mascwalletkey
            - AGENT_ID=mascagent
            - PORT=3032
            - SELF_URL=http://ma-sc-controller:3032
            - ADMIN_API_KEY=adminApiKey
        build:
            context: .
            dockerfile: Dockerfile
        image: ma-sc-controller
        container_name: ma-sc-controller
        ports:
            - "3032:3032"
        volumes:
            - ./:/www
        networks:
            - agency-network
        tty: true

    ma-mc-controller:
        environment:
            - MULTI_AGENT=true
            - MULTI_CONTROLLER=true
            - PORT=3033
            - SELF_URL=http://ma-mc-controller:3033
            - ADMIN_API_KEY=adminApiKey
            - STEWARD_URL=http://sa-sc-controller:3030
        build:
            context: .
            dockerfile: Dockerfile
        image: ma-mc-controller
        container_name: ma-mc-controller
        ports:
            - "3033:3033"
        volumes:
            - ./:/www
        networks:
            - agency-network
        tty: true
