# Docker compose to spin up aries-controller for demo purposes. This is a single-agent, single-controller configuration.
#
version: '3.5'

networks:
    agency-network:
        external: true

services:
    demo-controller:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.production
        image: demo-controller
        container_name: demo-controller
        working_dir: /www
        ports:
            - "3014:3013"
        expose:
            - "3014"
        volumes:
            - ./:/www
        networks:
            - agency-network
        tty: true
